---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres-configmap.yaml
  - postgres-service .yaml
  - postgres-deployment.yaml
  - service.yaml
  - deployment.yaml
