kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
<<<<<<< HEAD
  name: regionalpd-storageclass
  namespace: GH_USERNAME  
=======
  name: regionalpd-storageclass-github1
  namespace:  GH_USERNAME
>>>>>>> fcb3cf8506b7eeba84b191f638bf9742333fef30
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  replication-type: regional-pd
allowedTopologies:
  - matchLabelExpressions:
      - key: failure-domain.beta.kubernetes.io/zone
        values:
          - europe-west1-b
          - europe-west1-c
           
         
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pv
  namespace: GH_USERNAME  
spec:
  storageClassName: regionalpd-storageclass-github1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
