kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: regionalpd-storageclass
  namespace: GH_USERNAME  
provisioner: kubernetes.io/gce-pd
parameters:
  type:  pd-standard
  replication-type: regional-pd
allowedTopologies:
  - matchLabelExpressions:
      - key: failure-domain.beta.kubernetes.io/zone
        values:
          - europe-west1-b
          - europe-west1-c
           
         
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pv
  namespace: GH_USERNAME  
spec:
  storageClassName: regionalpd-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 
      

# Error from server (Invalid): error when applying patch:
# {"allowedTopologies":[{"matchLabelExpressions":[{"key":"failure-domain.beta.kubernetes.io/zone","values":["***-b"]}]}],"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"allowedTopologies\":[{\"matchLabelExpressions\":[{\"key\":\"failure-domain.beta.kubernetes.io/zone\",\"values\":[\"***-b\"]}]}],\"apiVersion\":\"storage.k8s.io/v1\",\"kind\":\"StorageClass\",\"metadata\":{\"annotations\":{},\"name\":\"regionalpd-storageclass\"},\"parameters\":{\"replication-type\":
# \"regional-pd\",\"type\":\"pd-standard\"},\"provisioner\":
# \"kubernetes.io/gce-pd\"}\n"}},"parameters":{"type":"pd-standard"}}      
