kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: regionalpd-storageclass-github
  namespace:  mohamedab2010
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  replication-type: regional-pd
allowedTopologies:
  - matchLabelExpressions:
      - key: failure-domain.beta.kubernetes.io/zone
        values:
          - europe-west1-b
          - europe-west1-c
           
         
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pv
  namespace: mohamedab2010  
spec:
  storageClassName: regionalpd-storageclass-github
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
