---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - namespace.yaml
  - postgres-pv.yaml
  - postgres-configmap.yaml
  - postgres-secret.yaml
  - postgres-service.yaml
  - postgres-deployment.yaml
  - service.yaml
  - deployment.yaml
