apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: prod
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: REGISTRY_HOSTNAME/arboreal-cosmos-346616/IMAGE:GITHUB_SHA
          #image: gcr.io/light-quest-349811/web-app@sha256:7cbc51fc3fb2954521d016ec6cd0a4ca5ee5f1261c961c46754f63b518ad54ce
          ports:
            - containerPort: 8069
          resources:
            limits:
              cpu: 300m            
            requests:
              cpu: 200m         
#when  go to prodction  must use limits cpu: 1   requests: cpu: 0.5 beacuse on my case the quota is limited.       
                 

          env:
          - name: DB_ENV_POSTGRES_USER
            valueFrom:
               secretKeyRef:
                 name: postgres-secret   
                 key: postgres-username

          - name: DB_ENV_POSTGRES_PASSWORD
            valueFrom:
               secretKeyRef:
                 name: postgres-secret    
                 key: postgres-password
   

          - name: DB_PORT_5432_TCP_ADDR
            valueFrom:
               configMapKeyRef:
                 name: postgres-configmap  
                 key: database_url                      
          volumeMounts:
            - name: my-pvc-nfs
              mountPath: "/mnt/data"
      volumes:
        - name: my-pvc-nfs
          persistentVolumeClaim:
            claimName: nfs     
---                      
         
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: web-app
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-app
  minReplicas: 1
  maxReplicas: 3
#in  prodction   maxReplicas: 12  should  beacuse on my case the quota is limited.                       

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 300Mi





                
