---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "web-app-service"
  namespace: "prod"
  labels:
    app: "web-app"
spec:
  ports:
    - protocol: "TCP"
      port: 8069
      targetPort: 8069
  selector:
    app: "web-app"
  type: "LoadBalancer"
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: odoo-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/limit-connections: '10'
    nginx.ingress.kubernetes.io/limit-rpm: '60'
    nginx.ingress.kubernetes.io/service-upstream: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
      - new.stage.inharf.xyz
      secretName: odoo-tls
  rules:
  - host: checkraiser.tinmua.vn
    http:
      paths:
      - backend:
          serviceName: web-app-service
          servicePort: 80  
